#!/bin/bash
if [[ "$IP" = "" ]]; then
domain=$(cat /etc/v2ray/domain)
else
domain=$IP
fi
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
echo "Checking Vps"
curl https://icanhazip.com
sleep 0.5
clear
                read -rp "User: " -e user
                CLIENT_EXISTS=$(grep -w $user /usr/local/etc/xray/config.json | wc -l)

                if [ ${CLIENT_EXISTS} == '1' ]; then
                        echo ""
                        echo "A client with the specified name was already created, please choose another name."
                        exit 1
                fi
        done
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/##vmess/a\### '"$user $exp"'\n{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""' '""$exp""'"},' /usr/local/etc/xray/config.json
sed -i '/##vless/a\## '"$user $exp"'\n{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""' '""$exp""'"},' /usr/local/etc/xray/config.json
#cat>/etc/v2ray/$user.json<<EOF
raw="{
      \"v\":\"2\",
      \"ps\":\"${user}\",
      \"add\":\"${domain}\",
      \"port\":\"443\",
      \"id\":\"${uuid}\",
      \"aid\":\"0\",
      \"net\":\"ws\",
      \"path\":\"/serverssh.net?${user}-${exp}\",
      \"type\":\"none\",
      \"host\":\"${domain}\",
      \"tls\":\"tls\"
}"
rawvless="$uuid@$domain:443?path=/serverssh?-${user}-${exp}&security=tls&encryption=none&host=${domain}&type=ws&sni=${domain}#${user}"
linkvmess=`echo -n ${raw} | base64 -w 0`
vmesslink="vmess://${linkvmess}"
vlesslink="vless://${rawvless}"
systemctl xray restart
service xray restart

clear
echo -e ""
echo -e "==========-V2RAY/VMESS-=========="
echo -e "Username       : ${user}"
echo -e "id             : ${uuid}"
echo -e "Expired        : $exp"
echo -e "================================="
echo -e "${vmesslink}"
echo -e "================================="
echo -e "${vlesslink}"
echo -e "================================="
